### ISSUE TITLE
[BUG] Pure Souls and Crying Souls interpolation causes unintended visual effects

### ISSUE THREAD

**Issue by GoldSlimeling91** [TeamPeril/Sculk-Hoard#10]
Due to the interpolation of the textures and the very nature of said textures being moving objects, the Pixels that are not there in the next frame will fade to black before fully vanishing for the next frame, causing a weird fade to black effect.
Its much more noticeable on the Pure Souls than it is on the Crying Souls

https://github.com/TeamPeril/Sculk-Horde/assets/111310936/840b7194-73a8-4ffa-bb0a-ae028d633d7f

**Comment by GoldSlimeling91** [comment]
A solution to this is just making the textures not interpolate, probably the only one too

**Comment by Mikeatron-User** [comment]
Thank you, it will be fixed in the next major update.
