### ISSUE TITLE
[BUG] Infect/Purify cursors can light on fire when they go near Lava or Fire

### ISSUE THREAD

**Issue by GoldSlimeling91** [TeamPeril/Sculk-Hoard#11]
![2023-09-16_17 48 10](https://github.com/TeamPeril/Sculk-Horde/assets/111310936/922aff1d-0c65-4af9-95c4-6ec3f8a6d093)

**Comment by Mikeatron-User** [comment]
Thank you, it will be fixed in the next major update.
