### ISSUE TITLE
Potential 1.19.2 version

### ISSUE THREAD

**Issue by Anorak01** [TeamPeril/Sculk-Hoard#12]
Hey, 

We're assembling a modpack for our server right now and wanted to try out Sculk Horde. I've tried compiling it a few times, but every time it gives me "geckolib not found"-ish error.
I assume the issue is known based on the latest commits, but are there any plans to potentially try to fix it?

Thanks in advance,
Anorak.

**Comment by Mikeatron-User** [comment]
Hi, Sculk Horde is only available on the following versions: 1.16.5, 1.19.4, and 1.20.1. This likely is the cause of your issue.

The 1.20.1 version of our mod is the only version recieving updates.

**Comment by Anorak01** [comment]
I tried compiling the 1.19.2 branch. As a matter of fact, I figured out the issue and will be making a pull request for it.

**Comment by Mikeatron-User** [comment]
> I tried compiling the 1.19.2 branch. As a matter of fact, I figured out the issue and will be making a pull request for it.

That branch is dead. I attempted a 1.19.2 port but never finished it. Nothing about it works. There are currently no plans to finish it.

**Comment by Anorak01** [comment]
I see, okay.

Welp, thanks for your time

**Comment by Mikeatron-User** [comment]
Have a wonderful day :)
