### ISSUE TITLE
Crash due to ticking entity

### ISSUE THREAD

**Issue by BlazeKin** [TeamPeril/Sculk-Hoard#14]
"Neruina cannot handle this exception. Please report this to the culprit mod author." So here I am doing just that, I think it's sculk trying to infect an alex's mob. I don't really know. I just added this mod to an existing world, reloaded spawn to get the tomb to start and now I'm crashing near it. 
[crash-2023-11-18_23.20.41-client.txt](https://github.com/TeamPeril/Sculk-Horde/files/13402232/crash-2023-11-18_23.20.41-client.txt)

**Comment by Mikeatron-User** [comment]
This was resolved in the latest patch
