### ISSUE TITLE
Sculk stopped working on 1.20.1

### ISSUE THREAD

**Issue by Jakub2212** [TeamPeril/Sculk-Hoard#15]
Spreads super slowly, doesn't spawn mobs other than bees and spewers, block of sculk mass dissapears after placing it in creative mode. difficulty is set to hard.

**Comment by Mikeatron-User** [comment]
**It would be helpful to know the following information**

1. What version of Minecraft are you using?
2. What version of forge are you using?
3. What version of the mod are you using?

**Comment by Jakub2212** [comment]
1.20.1
47.2.0
sculkhorde-1.20.1-0.7.8

**Comment by Mikeatron-User** [comment]
> 1.20.1
> 47.2.0
> sculkhorde-1.20.1-0.7.8

Have you tried updating to the latest version to resolve the issue.

**Comment by Jakub2212** [comment]
updating didn't fix it. In case you want to ask for mods/world next:
Mod Profile: https://drive.google.com/file/d/1-Sj2LfrADdXfz4YEODtVu97EiSvPI3Zq/view?usp=drive_link
World: https://drive.google.com/file/d/1tn1Wf9sEXYxgha_1bjttJs0BP8KHMMYf/view?usp=sharing

**Comment by Mikeatron-User** [comment]
Try updating again

**Comment by Jakub2212** [comment]
Yea seems to work now, it spreads, spawns the phantoms, it doesn't seem to
spawn any other aggressive mobs when i destroy skulk blocks in creative
mode tho, idk if that's intentional and only works in survival?

śr., 13 gru 2023 o 03:11 Mike ***@***.***> napisał(a):

**Comment by Mikeatron-User** [comment]
It is intentional.
