### ISSUE TITLE
[Suggestion] Have the sculks absorb/delete "organic" items dropped onto them.

### ISSUE THREAD

**Issue by Poke5555** [TeamPeril/Sculk-Hoard#18]
Ive noticed (especially with mods that increase leaf decay rate) in densely forested areas that hundreds to thousands of saplings/apples/sticks will pile up on the ground causing tps/fps drops. Plus adding a survival way of "feeding" the sculk would be cool.

**Comment by Mikeatron-User** [comment]
I will add something like this eventually.
