### ISSUE TITLE
Crash 1.19.2 Hello 1.19.2. I create a new world and then the game crashes. Mods conflict. You can make it compatible.

### ISSUE THREAD

**Issue by Sauron2024** [TeamPeril/Sculk-Hoard#23]
I have installed the Sculk Horde mod. After that, an error occurred. The game starts. But when I create a new world. The game is crashing.
Hello 1.19.2. I create a new world and then the game crashes. Mods conflict. You can make it compatible.

[crash-2023-12-15_11.53.46-server.txt](https://github.com/TeamPeril/Sculk-Horde/files/13688127/crash-2023-12-15_11.53.46-server.txt)
[debug.log](https://github.com/TeamPeril/Sculk-Horde/files/13688128/debug.log)
[latest.log](https://github.com/TeamPeril/Sculk-Horde/files/13688129/latest.log)

**Comment by Mikeatron-User** [comment]
Doesn't Seem to be an issue with my mod, looks like immersive petrolium.
