### ISSUE TITLE
sculk logs do not retain original orientation

### ISSUE THREAD

**Issue by rabbitscreams** [TeamPeril/Sculk-Hoard#24]
**Minecraft Version:** 1.20.1
**Forge Version:** 47.2.0
**Mod Version:** 1.20.1-0.7.22
**Additional Information:** using Sculk Horde Survival modpack, version 1.20-1.2.5

when sculk infests a log, the sculk-infested version is vertical only, and has no orientation even when deliberately placed sideways. while only a cosmetic bug, it'd be nice to have logs retain their original orientation.

![2023-12-17_15 11 28](https://github.com/TeamPeril/Sculk-Horde/assets/57117544/57d98b2a-bd78-4586-8088-18b634d7f95d)

additionally, wood/bark blocks are converted into logs upon infestation.

![2023-12-17_15 15 59](https://github.com/TeamPeril/Sculk-Horde/assets/57117544/1e9dea5a-9d9c-4916-9aa0-c33231bdf9ba)

**Comment by Mikeatron-User** [comment]
I will add this eventually, but for now its low priority.
