### ISSUE TITLE
[suggestion] allow the ability to render sculk-infested blocks inert for decorative purposes

### ISSUE THREAD

**Issue by rabbitscreams** [TeamPeril/Sculk-Hoard#25]
some of the sculk-infested blocks are really beautiful (i especially love the look of sculk-infested wood) and it would be very neat if you could harvest the blocks for decorating. unfortunately, infested wood is not even in the creative tab, and infested logs cannot be crafted into the planks. it'd also be nice to have infested versions of stairs, slabs, fences, doors and trapdoors, perhaps only craftable from the inert versions? since infestation cannot infect these blocks by default.

the recipe could be something simple to render it inert, not too expensive but still a bit of effort, like surrounding a gold nugget in the blocks you wish to render inert, or something like that. just having some kind of safe access to sculk-infested blocks for decorative reasons at all would be nice either way though.

**Comment by Mikeatron-User** [comment]
This may be something I add in the future, thought it is not a high priority.
