### ISSUE TITLE
[Suggestion] Configurable list of mobs and/or mod ids to prevent mob attacks

### ISSUE THREAD

**Issue by BlueDuckYT** [TeamPeril/Sculk-Hoard#26]
I'm working on a 1.19.2 zombie apocalypse modpack themed around the sculk and it would be nice if there was a way to prevent the sculk creatures from attacking vanilla zombies and rotten creatures' zombies

**Comment by Mikeatron-User** [comment]
Great idea, ill see about implementing this in the future
