### ISSUE TITLE
[Suggestion] An item to find Sculk Nodes

### ISSUE THREAD

**Issue by ghost** [TeamPeril/Sculk-Hoard#29]
I have one complaint with Sculk Nodes: **They can be incredibly hard to find**.

Sure there's telltale signs of being near a node from the heartbeat, but I think it can only help so much if the node is spawned somewhere that is really hidden.

I think having an item that can help locate Sculk Nodes would make fighting the Horde streamlined, so to speak.

**An idea for the item in question**:

The item will be called a Node Detector.

 The item will help locate the nearest Sculk Node from the player. It has three statuses: green, yellow, and red. 

Green means it's detecting a Node, but it's pretty far. (about 76-200 blocks away)
Yellow means the player is close to the Node. (26-75 blocks away)
Red means you're at the source. (0-25 blocks away)

To get a Node Detector, you need a compass, four crying souls, and four living rocks (The thing found in the spires made by the Sculk Node).

 I don't want the item to be completely OP, so maybe after the player destroys a Node, the Detector is on cooldown for 5-10 minutes, and then it will find another Node after the cooldown.

**Comment by Mikeatron-User** [comment]
We have an item in the works already for this, though you've given some great ideas.

**Comment by ghost** [comment]
Nice, can't wait to see this new item.
