### ISSUE TITLE
Duplicate from curse just in case

### ISSUE THREAD

**Issue by vasmark1** [TeamPeril/Sculk-Hoard#3]
Idk if this a bug or planned feature or not, but I'll mention it here :/

1.19.4 Purification Flast deals 50 damage to all mobs in game, not tested on players. Also it's ultimate way to kill any boss, like Warden or ED only with 4 or 6 bottles. 

Also, infused mobs are spawning and detecting wardens like enemies, so it becomes infinitely lasting combat of sculk and modded sculk. 

Great thanks for your work! As a person who used to play tc4 with its infection mechanics I found Gravemind a bit OP for singleplayer, because even in late-late game it consumes all of your recourses to hold horde back, not to attack it's heart. 

Not tested in big mp, only in 2 person lobby, cuz i don't have friends. :(

**Comment by Mikeatron-User** [comment]
Thanks for letting me know about this oversight. The flask is not supposed to do any damage, but just clean up infestation. This will be resolved in the next update.
