### ISSUE TITLE
Infection from Mass Dev Infectionator 3000 seems slow?

### ISSUE THREAD

**Issue by ghost** [TeamPeril/Sculk-Hoard#30]
I was messing around with the new update for Sculk Horde, and tried testing out stuff between a mass dev block and the infestation ward block, this caused me to disconnect from my single player world.

So I made another world with only sculk horde and two performance mods installed to see if Sculk Horde was broken. It wasn't, but I noticed that the infection speed of the Mass Dev Block was noticeably slow or laggy.

Replicating this issue can be found in this video made:
https://youtu.be/1412G3RVMhM

Mods installed:
embeddium-0.2.16+mc1.20.1
embeddiumplus-1.20.1-v1.2.1
geckolib-forge-1.20.1-4.4
sculkhorde-1.20.1-0.8.3
textrues_embeddium_options-0.1.3+mc1.20.1

MC Version: 1.20.1
Mod Launcher: Forge 47.2.19
OS: Windows 11

**Comment by Mikeatron-User** [comment]
Fixed this in the latest update 1.20.1-0.8.4
