### ISSUE TITLE
[Suggestion]: Special death animation for Sculk Enderman

### ISSUE THREAD

**Issue by ghost** [TeamPeril/Sculk-Hoard#32]
The Sculk Enderman is a boss for the Sculk Horde mod, so I believe that it should be given a death animation fitting for a boss mob. 

I had two ideas for the death animation:

1. It dies like the Mutant Enderman from Mutant Creatures, but it releases spores that gives you the lure effect.
2. The Enderman disintegrates, starting from the legs, and ending the animation at the head.

After said death animation, the loot of the Sculk Enderman is dropped.

**Comment by Mikeatron-User** [comment]
Yea we'll do this at some point
