### ISSUE TITLE
Exception while adding particle Crash

### ISSUE THREAD

**Issue by Leo0806-studios** [TeamPeril/Sculk-Hoard#36]
sculkhorde-1.20.1-0.8.9.jar
Forge 47.2.0
Minecraft 1.20.1
[hs_err_pid25744.log](https://github.com/TeamPeril/Sculk-Horde/files/14072773/hs_err_pid25744.log)
[crash-2024-01-27_16.06.30-server.txt](https://github.com/TeamPeril/Sculk-Horde/files/14072775/crash-2024-01-27_16.06.30-server.txt)

**Comment by Mikeatron-User** [comment]
I will look into this

**Comment by Mikeatron-User** [comment]
Update the mod
