### ISSUE TITLE
[Bug]: Texture of Soul Harvester Particles are Missing

### ISSUE THREAD

**Issue by ghost** [TeamPeril/Sculk-Hoard#37]
When breaking the new Soul Harvester, its particles are missing.

https://github.com/TeamPeril/Sculk-Horde/assets/148708399/9c9b9507-b7be-4149-8785-2b3b5a57cbed

Mod Loader: Forge 47.2.19
Minecraft Version: 1.20.1
OS: Windows 11

Mods:
  [✔] additional_enchantments-1.20.1-0.3.5-all
  [✔] additionaladditions-6.0.1
  [✔] alternategunpowder-1.0.0-1.20.1
  [✔] autohud-6.3.4+1.20.1-forge
  [✔] backpacked-forge-1.20.1-2.2.5
  [✔] better-trees-1.7
  [✔] CerbonsAPI-Forge-1.20.1-1.1.0
  [✔] CerbonsBetterBeacons-Forge-1.20.1-1.1.1
  [✔] do_a_barrel_roll-forge-3.5.0+1.20.1
  [✔] dynamiccrosshair-7.4.4+1.20-forge
  [✔] EasyAnvils-v8.0.1-1.20.1-Forge
  [✔] EasyMagic-v8.0.1-1.20.1-Forge
  [✔] elytra_physics-forge-2.0
  [✔] ElytraBombing-Forge-1.20.1-1.0.0
  [✔] embeddium-0.2.18+mc1.20.1
  [✔] embeddiumplus-1.20.1-v1.2.3-build
  [✔] EnchantingInfuser-v8.0.2-1.20.1-Forge
  [✔] framework-forge-1.20.1-0.6.16
  [✔] geckolib-forge-1.20.1-4.4.2
  [✔] jei-1.20.1-forge-15.2.0.27
  [✔] oculus-mc1.20.1-1.6.13
  [✔] paddedelytras-1.20-1.0
  [✔] PuzzlesLib-v8.1.14-1.20.1-Forge
  [✔] sculkhorde-1.20.1-0.9.0-Beta1
  [✔] squaremap-forge-mc1.20.1-1.2.0
  [✔] textrues_embeddium_options-0.1.3+mc1.20.1
  [✔] UniversalEnchants-v8.0.0-1.20.1-Forge
  [✔] witherstormmod-1.20.1-4.0.1.1

**Comment by Mikeatron-User** [comment]
Thank you for your report, it will be resolved.

**Comment by Mikeatron-User** [comment]
Resolved
