### ISSUE TITLE
I made a simplified Chinese document, hoping to be added to a later version THANKYOU

### ISSUE THREAD

**Issue by shenyx110** [TeamPeril/Sculk-Hoard#4]
我做了一个简体中文汉化文件 希望可以追加到后续版本

I made a simplified Chinese document, hoping to be added to a later version.

{
  "itemGroup.sculkhorde_tab": "幽匿部落",
  "effect.sculkhorde.sculk_infected": "埋藏",
  "item.sculkhorde.sculk_matter": "幽匿主题",
  "item.sculkhorde.dev_wand": "开发魔杖",
  "tooltip.sculkhorde.dev_wand": "右键单击以生成幽匿孢子，以开始世界感染\n右键单击+左shift键以显示总幽匿质量 \n右键单击+左alt键以添加100个幽匿质量.",
  "tooltip.sculkhorde.dev_wand.shift": "\u00A75JoeMama",
  "item.sculkhorde.dev_conversion_wand": "开发转换魔杖",
  "tooltip.sculkhorde.dev_conversion_wand": "将块转换为受感染的变体 ",
  "item.sculkhorde.infestation_purifier": "净化感染",
  "tooltip.sculkhorde.infestation_purifier": "右键单击以返回物品 \n当它死亡时，物品不会掉落 \n当一个实体产生时，会从该地区清除幽匿感染 如果它在其范围内找不到更多的幽匿感染则会下降 此外，幽匿部落会攻击它 ",
  "item.sculkhorde.purification_flask_item": "净化瓶",
  "tooltip.sculkhorde.purification_flask_item": "投掷到感染上净化它",
  "item.sculkhorde.custom_item_projectile": "物品抛射物",
  "tooltip.sculkhorde.custom_item_projectile": "这是一个测试弹丸的开发项目 它是所有弹丸的父类 我决定把它添加为只为珠宝准备的物品",
  "item.sculkhorde.sculk_acidic_projectile": "酸性质量",
  "tooltip.sculkhorde.sculk_acidic_projectile": "由幽匿喷头产生的酸性弹丸\n当弹丸击中方块时，有机会掉落 ",
  "item.sculkhorde.sculk_resin": "幽匿树脂",
  "tooltip.sculkhorde.sculk_resin": "一种粘性和可延展的物质 \n可以通过剪切幽匿蜂巢结构的成熟细胞获得",
  "item.sculkhorde.calcite_clump": "幽匿方解石团",
  "item.sculkhorde.dev_node_spawner": "开发幽匿主茎发生器",
  "tooltip.sculkhorde.dev_node_spawner": "在玩家的位置创造幽匿感染",
  "tooltip.sculkhorde.calcite_clump": "一种像骨头一样的材料 \n可以在幽匿活岩结构开采幽匿方解石矿石获得",
  "block.sculkhorde.calcite_ore": "幽匿方解石矿",
  "tooltip.sculkhorde.calcite_ore": "坚固的骨状材料 \n可以从幽匿生活岩石结构中获得 最常见在幽匿主茎周围",
  "block.sculkhorde.ancient_large_bricks": "古代大型幽匿砖",
  "block.sculkhorde.ancient_large_tile": "古代大型幽匿瓷砖",
  "block.sculkhorde.crust": "幽匿外壳",
  "block.sculkhorde.infested_log": "受感染的日志",
  "tooltip.sculkhorde.infested_log": "一种欺骗性的，看起来像木头的材料，由一种奇怪的、像骨头一样的材料制成的？",
  "block.sculkhorde.infested_stone": "感染石块",
  "tooltip.sculkhorde.infested_stone": "一种像石头一样的感染材料",
  "block.sculkhorde.infested_andesite": "感染安山岩",
  "tooltip.sculkhorde.infested_andesite": "一种像安山岩一样的感染材料.",
  "block.sculkhorde.infested_granite": "感染花岗岩",
  "tooltip.sculkhorde.infested_granite": "一种像花岗岩一样的感染材料",
  "block.sculkhorde.infested_diorite": "感染长闪岩",
  "tooltip.sculkhorde.infested_diorite": "一种像长闪岩一样的感染材料",
  "block.sculkhorde.infested_sand": "感染沙",
  "tooltip.sculkhorde.infested_sand": "一种像沙一样的感染材料",
  "block.sculkhorde.infested_sandstone": "感染砂岩",
  "tooltip.sculkhorde.infested_sandstone": "一种像砂岩一样的感染材料",
  "block.sculkhorde.infested_deepslate": "感染深板岩",
  "tooltip.sculkhorde.infested_deepslate": "一种像深板岩一样的感染材料",
  "block.sculkhorde.sculk_node": "幽匿主茎",
  "tooltip.sculkhorde.sculk_node": "在幽匿部落中发现的一个高度复杂的神经中枢。它充当幽匿节点的辅助大脑，促进了对本地幽匿网络的复杂控制",
  "block.sculkhorde.spike": "幽匿尖刺",
  "tooltip.sculkhorde.spike": "一个尖锐而危险的尖刺 \n感染所有接触它的生物，与非幽匿实体接触后立即断裂",
  "block.sculkhorde.grass": "幽匿草丛",
  "block.sculkhorde.grass_short": "幽匿短草",
  "block.sculkhorde.tendrils": "幽匿卷须藤",
  "tooltip.sculkhorde.tendrils": "一种藤蔓状的植物群，看起来像某种组织",
  "block.sculkhorde.small_shroom": "小幽匿菇",
  "block.sculkhorde.sculk_shroom_culture": "幽匿蘑文化？",
  "block.sculkhorde.cocoon": "幽匿卵",
  "block.sculkhorde.cocoon_root": "幽匿卵茎",
  "block.sculkhorde.sculk_mass": "幽匿弥撒块",
  "block.sculkhorde.sculk_dura_matter": "幽匿硬脑脊膜",
  "block.sculkhorde.sculk_arachnoid": "幽匿蛛网膜",
  "block.sculkhorde.sculk_summoner": "幽匿召唤者",
  "tooltip.sculkhorde.sculk_summoner": "一个奇怪而神秘的方块，能召唤幽匿部落成员。\n一旦被激活，将更快地产生敌人.",
  "block.sculkhorde.sculk_bee_nest": "幽匿蜂巢",
  "tooltip.sculkhorde.sculk_bee_nest": "一个类似蜂巢的结构，是幽匿蜜蜂群的家 \n它下面的细胞可以收获幽匿树脂",
  "block.sculkhorde.sculk_bee_nest_cell": "幽匿蜂巢细胞",
  "tooltip.sculkhorde.sculk_bee_nest_cell": "一个拥有幽匿蜜蜂群的细胞 \n成熟后，可以用剪刀收获幽匿树脂",
  "block.sculkhorde.sculk_living_rock": "幽匿活岩",
  "block.sculkhorde.sculk_living_rock_root": "幽匿活岩根",
  "block.sculkhorde.dev_structure_tester": "开发结构测试仪",
  "tooltip.sculkhorde.dev_structure_tester": "这是一个用于测试结构的开发物品。它将在的放置的位置产生一个结构",
  "entity.sculkhorde.sculk_zombie": "幽匿僵尸",
  "entity.sculkhorde.sculk_spitter": "幽匿弓手",
  "entity.sculkhorde.sculk_mite": "幽匿螨",
  "entity.sculkhorde.sculk_mite_aggressor": "幽匿侵略螨",
  "entity.sculkhorde.sculk_hatcher": "幽匿奶牛",
  "entity.sculkhorde.sculk_bee_harvester": "幽匿收割蜂",
  "entity.sculkhorde.sculk_bee_infector": "幽匿传染蜂",
  "entity.sculkhorde.sculk_spore_spewer": "幽匿孢子传播者",
  "entity.sculkhorde.infestation_purifier": "袭扰净化者"

}

**Comment by Mikeatron-User** [comment]
谢谢，我会在下一个更新中添加。

**Comment by shenyx110** [comment]
Yesterday, I tested and made some more appropriate translation modifications.

昨天我经测试做出了 一些更贴切的翻译修改

{
  "itemGroup.sculkhorde_tab": "幽匿部落",
  "effect.sculkhorde.sculk_infected": "埋藏",
  "item.sculkhorde.sculk_matter": "幽匿蔟",
  "item.sculkhorde.dev_wand": "(开发者)魔杖",
  "tooltip.sculkhorde.dev_wand": "右键单击以生成幽匿孢子，以开始世界感染\n右键单击+左shift键以显示总幽匿质量 \n右键单击+左alt键以添加100个幽匿质量.",
  "tooltip.sculkhorde.dev_wand.shift": "\u00A75JoeMama",
  "item.sculkhorde.dev_conversion_wand": "(开发者)转换魔杖",
  "tooltip.sculkhorde.dev_conversion_wand": "将块转换为受感染的变体 ",
  "item.sculkhorde.infestation_purifier": "净化感染",
  "tooltip.sculkhorde.infestation_purifier": "右键单击以返回物品 \n当它死亡时，物品不会掉落 \n当一个实体产生时，会从该地区清除幽匿感染 如果它在其范围内找不到更多的幽匿感染则会下降 此外，幽匿部落会攻击它 ",
  "item.sculkhorde.purification_flask_item": "净化瓶",
  "tooltip.sculkhorde.purification_flask_item": "投掷到感染上净化它",
  "item.sculkhorde.custom_item_projectile": "物品抛射物",
  "tooltip.sculkhorde.custom_item_projectile": "这是一个测试弹丸的(开发者)项目 它是所有弹丸的父类 我决定把它添加为只为珠宝准备的物品",
  "item.sculkhorde.sculk_acidic_projectile": "酸性质量",
  "tooltip.sculkhorde.sculk_acidic_projectile": "由幽匿喷头产生的酸性弹丸\n当弹丸击中方块时，有机会掉落 ",
  "item.sculkhorde.sculk_resin": "幽匿树脂",
  "tooltip.sculkhorde.sculk_resin": "一种粘性和可延展的物质 \n可以通过剪切幽匿蜂巢结构的成熟细胞获得",
  "item.sculkhorde.calcite_clump": "幽匿方解石团",
  "item.sculkhorde.dev_node_spawner": "(开发者)幽匿主茎发生器",
  "tooltip.sculkhorde.dev_node_spawner": "在玩家的位置创造幽匿感染",
  "tooltip.sculkhorde.calcite_clump": "一种像骨头一样的材料 \n可以在幽匿活岩结构开采幽匿方解石矿石获得",
  "block.sculkhorde.calcite_ore": "幽匿方解石矿",
  "tooltip.sculkhorde.calcite_ore": "坚固的骨状材料 \n可以从幽匿生活岩石结构中获得 最常见在幽匿主茎周围",
  "block.sculkhorde.ancient_large_bricks": "古代大型幽匿砖",
  "block.sculkhorde.ancient_large_tile": "古代大型幽匿瓷砖",
  "block.sculkhorde.crust": "幽匿外壳",
  "block.sculkhorde.infested_log": "受感染的日志",
  "tooltip.sculkhorde.infested_log": "一种欺骗性的，看起来像木头的材料，由一种奇怪的、像骨头一样的材料制成的？",
  "block.sculkhorde.infested_stone": "感染石块",
  "tooltip.sculkhorde.infested_stone": "一种像石头一样的感染材料",
  "block.sculkhorde.infested_andesite": "感染安山岩",
  "tooltip.sculkhorde.infested_andesite": "一种像安山岩一样的感染材料.",
  "block.sculkhorde.infested_granite": "感染花岗岩",
  "tooltip.sculkhorde.infested_granite": "一种像花岗岩一样的感染材料",
  "block.sculkhorde.infested_diorite": "感染长闪岩",
  "tooltip.sculkhorde.infested_diorite": "一种像长闪岩一样的感染材料",
  "block.sculkhorde.infested_sand": "感染沙",
  "tooltip.sculkhorde.infested_sand": "一种像沙一样的感染材料",
  "block.sculkhorde.infested_sandstone": "感染砂岩",
  "tooltip.sculkhorde.infested_sandstone": "一种像砂岩一样的感染材料",
  "block.sculkhorde.infested_deepslate": "感染深板岩",
  "tooltip.sculkhorde.infested_deepslate": "一种像深板岩一样的感染材料",
  "block.sculkhorde.sculk_node": "幽匿主茎",
  "tooltip.sculkhorde.sculk_node": "在幽匿部落中发现的一个高度复杂的神经中枢。它充当幽匿节点的辅助大脑，促进了对本地幽匿网络的复杂控制",
  "block.sculkhorde.spike": "幽匿尖刺",
  "tooltip.sculkhorde.spike": "一个尖锐而危险的尖刺 \n感染所有接触它的生物，与非幽匿实体接触后立即断裂",
  "block.sculkhorde.grass": "幽匿草丛",
  "block.sculkhorde.grass_short": "幽匿短草",
  "block.sculkhorde.tendrils": "幽匿卷须藤",
  "tooltip.sculkhorde.tendrils": "一种藤蔓状的植物群，看起来像某种组织",
  "block.sculkhorde.small_shroom": "小幽匿菇",
  "block.sculkhorde.sculk_shroom_culture": "幽匿蘑群",
  "block.sculkhorde.cocoon": "幽匿卵",
  "block.sculkhorde.cocoon_root": "幽匿卵茎",
  "block.sculkhorde.sculk_mass": "幽匿弥撒块",
  "block.sculkhorde.sculk_dura_matter": "幽匿硬脑脊膜",
  "block.sculkhorde.sculk_arachnoid": "幽匿蛛网膜",
  "block.sculkhorde.sculk_summoner": "幽匿召唤者",
  "tooltip.sculkhorde.sculk_summoner": "一个奇怪而神秘的方块，能召唤幽匿部落成员 \n 一旦被激活，将更快地产生敌人",
  "block.sculkhorde.sculk_bee_nest": "幽匿蜂巢",
  "tooltip.sculkhorde.sculk_bee_nest": "一个类似蜂巢的结构，是幽匿蜜蜂群的家 \n 它下面的细胞可以收获幽匿树脂",
  "block.sculkhorde.sculk_bee_nest_cell": "幽匿蜂巢细胞",
  "tooltip.sculkhorde.sculk_bee_nest_cell": "一个拥有幽匿蜜蜂群的细胞 \n 成熟后，可以用剪刀收获幽匿树脂",
  "block.sculkhorde.sculk_living_rock": "幽匿活岩",
  "block.sculkhorde.sculk_living_rock_root": "幽匿活岩根",
  "block.sculkhorde.dev_structure_tester": "(开发者)结构测试仪",
  "tooltip.sculkhorde.dev_structure_tester": "这是一个用于测试结构的工具 \n 它将在的放置的位置产生一个结构",
  "entity.sculkhorde.sculk_zombie": "幽匿僵尸",
  "entity.sculkhorde.sculk_spitter": "幽匿弓手",
  "entity.sculkhorde.sculk_mite": "幽匿螨",
  "entity.sculkhorde.sculk_mite_aggressor": "幽匿侵略螨",
  "entity.sculkhorde.sculk_hatcher": "幽匿奶牛",
  "entity.sculkhorde.sculk_bee_harvester": "幽匿收割蜂",
  "entity.sculkhorde.sculk_bee_infector": "幽匿传染蜂",
  "entity.sculkhorde.sculk_spore_spewer": "幽匿孢子传播者",
  "entity.sculkhorde.infestation_purifier": "袭扰净化者"

}
