### ISSUE TITLE
Advancement 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [TeamPeril/Sculk-Hoard#40]
sculkhorde-1.19.2-0.8.1.jar

> [05:14:14] [Render thread/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement sculkhorde:craft_infestation_purifier: Invalid criterion trigger: minecraft:recipe_crafted
> [05:14:14] [Render thread/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement sculkhorde:craft_pure_souls: Invalid criterion trigger: minecraft:recipe_crafted
> [05:14:14] [Render thread/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement sculkhorde:craft_purification_flask: Expected item to be an item, was unknown string 'sculkhorde:purity_splash_potion'
> [05:14:14] [Render thread/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement sculkhorde:craft_infestation_ward_block: Invalid criterion trigger: minecraft:recipe_crafted
> [05:14:14] [Render thread/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement minecraft:adventure/craft_decorated_pot_using_only_sherds: Invalid criterion trigger: minecraft:recipe_crafted
> [05:14:14] [Render thread/ERROR] [minecraft/ServerAdvancementManager]: Parsing error loading custom advancement sculkhorde:craft_essence_of_purity: Invalid criterion trigger: minecraft:recipe_crafted
> 
>

**Comment by Mikeatron-User** [comment]
Issue #44 was fixed.
