### ISSUE TITLE
TPS Down 1.19.2 Forge 

### ISSUE THREAD

**Issue by Krimatoria** [TeamPeril/Sculk-Hoard#41]
1. sculkhorde-1.19.2-0.8.1.jar
2. observable-3.3.1.jar
3. spark-1.10.37-forge.jar
4. azurelib-forge-1.19.2-1.0.41.jar
5. geckolib-forge-1.19-3.1.40.jar

com.github.sculkhorde.common.entity.infection.CursorEntity.tick()16.10%

> [28Feb2024 19:38:10.216] [Render thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class net.minecraft.world.entity.animal.Bee from class com.github.sculkhorde.common.entity.SculkBeeHarvesterEntity
> [28Feb2024 19:38:10.216] [Render thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class com.github.sculkhorde.common.entity.boss.sculk_enderman.SculkEndermanEntity from class com.github.sculkhorde.common.entity.SculkSporeSpewerEntity
> [28Feb2024 19:38:10.218] [Render thread/WARN] [net.minecraft.network.syncher.SynchedEntityData/]: defineId called for: class com.github.sculkhorde.common.entity.boss.sculk_enderman.SculkEndermanEntity from class com.github.sculkhorde.common.entity.SculkPhantomCorpseEntity
[28Feb2024 19:38:23.408] [Worker-ResourceReload-5/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Exception loading blockstate definition: 'sculkhorde:blockstates/soul_harvester.json' missing model for variant: 'sculkhorde:soul_harvester#'
[28Feb2024 19:38:30.780] [Worker-ResourceReload-5/WARN] [net.minecraft.client.resources.model.ModelBakery/]: Unable to load model: 'sculkhorde:soul_harvester#inventory' referenced from: sculkhorde:soul_harvester#inventory: java.io.FileNotFoundException: sculkhorde:models/item/soul_harvester.json
[28Feb2024 19:39:55.737] [Server thread/ERROR] [com.github.sculkhorde.core.SculkHorde/]: BlockEntityChunkLoaderHelper is null. Cannot Load

<details>
<summary> Observable / Spark </summary>

![image](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/1346670d-96ec-4b23-abcf-916ef35230f4)
![image](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/ce1b48bb-5667-4f7f-8146-49e6012c9237)
![image](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/1e3857aa-7890-49b4-84cf-7f60114a19ca)
![image](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/aa0b0ecf-9152-4a83-8f23-0ca515143f9c)
![image](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/258ff31b-892e-4607-b035-3551c870da7d)
![image](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/04f18091-5263-4087-8dbd-4952e0774e59)

</details>

<details>
<summary> TPS Mobs </summary>

![2024-02-28_19 40 18](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/554bb4a4-1a7b-4672-a503-64da18f02e62)
![2024-02-28_19 46 11](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/3793bd8f-644e-455c-801a-4613448cccfd)
![2024-02-28_19 42 58](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/f2a6959f-90a1-4d21-8a18-f843d4255242)
![2024-02-28_19 43 44](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/1357cc23-950c-47cf-b5b3-fc76e59411b9)
![2024-02-28_20 32 10](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/ab640c48-c58c-4eb5-8bc7-5d57da11c20d)
![2024-02-28_19 30 10](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/9579393a-0528-462a-bb4d-08714d9131a3)
![2024-02-28_19 42 58](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/e9e24107-0bad-4080-a355-f98aabcef925)
![2024-02-28_04 30 26](https://github.com/TeamPeril/Sculk-Horde/assets/106809386/8d06fdda-5b8a-4506-b6b8-e06d27caff46)

</details>

I hope it helps if this information is useful)

**Comment by Mikeatron-User** [comment]
Use a performance mod like embeddium and radium reforged.
