### ISSUE TITLE
Block Load 1.19.2 Forge

### ISSUE THREAD

**Issue by Krimatoria** [TeamPeril/Sculk-Hoard#42]
- spore_1.19_2_2.0.2c.jar 
- cultofthewither2.4.jar - harvester mob
- sculkhorde-1.19.2-0.8.1.jar
- deeperdarker-forge-1.19.2-1.2.2.jar
- Deep Dark Regrowth 1.2.4.3.jar

> [28Feb2024 19:20:23.421] [Server thread/ERROR] [com.github.sculkhorde.core.SculkHorde/]: BlockEntityChunkLoaderHelper is null. Cannot Load
> [28Feb2024 19:30:49.275] [Server thread/WARN] [net.minecraft.world.level.chunk.LevelChunk/]: Tried to load a DUMMY block entity @ BlockPos{x=7, y=-12, z=353} but found not block entity block Block{minecraft:cave_air} at location
> [28Feb2024 19:30:49.275] [Server thread/WARN] [net.minecraft.world.level.chunk.LevelChunk/]: Tried to load a block entity for block Block{minecraft:cave_air} but failed at location BlockPos{x=7, y=-12, z=353}**

**Comment by Mikeatron-User** [comment]
This will be fixed in the future. It isn't that important.
