### ISSUE TITLE
Game crashes and world becomes corrupted/unplayable

### ISSUE THREAD

**Issue by Cod1ngGamer** [TeamPeril/Sculk-Hoard#51]
I was messing around with the mod in creative, and a sculk enderman was scouting an area right next to the sculk tomb. I was summoning evokers around it, trying to see if they could kill it, and the game crashed. Can't load up the world anymore.
I didn't really lose anything because I just made the world like 15 minutes ago, but this could seriously ruin someone's day.
Here's the log:
[crash-2024-05-10_23.01.02-server.txt](https://github.com/TeamPeril/Sculk-Horde/files/15281454/crash-2024-05-10_23.01.02-server.txt)

Extra info: I'm using Modrinth, windows 11, and I got the crash report from Not Enough Crashes. Here's a modlist:
[modlist.txt](https://github.com/TeamPeril/Sculk-Horde/files/15281462/modlist.txt)

The vexes were infected with Burrowed and Diseased Cysts, so I think when those ran out, the game had an aneurism or something. It's also worth noting that I made the evokers go after the sculk enderman using mob battle mod, so the vexes were mad at it as well.

**Comment by Cod1ngGamer** [comment]
I found the source of the crash! A vex was infected with burrowed, and inside bedrock at the bottom of the world. The game tried to replace the bedrock with a block of sculk mass, but couldn't, either because it's bedrock, or more likely, because the block below was void. It's kind of a circumstantial crash, but still should be looked into relatively quickly.

Interesting note: when the crash occurs, it actually displays the error message "Server closed" and the world becomes corrupted, but the game doesn't initially crash. If you try to load it back up again, the game crashes. Apparently, Minecraft worlds actually run on a local server, so the crash is definitely happening on the server side.

**Comment by Mikeatron-User** [comment]
This will be resolved in the next major update.
