### ISSUE TITLE
[Suggestion] Make the Warden not attack sculk mobs

### ISSUE THREAD

**Issue by Cod1ngGamer** [TeamPeril/Sculk-Hoard#52]
It kind of makes sense, after all. The Warden is the classic sculk mob. Maybe they can defend the ancient sculk brain node in the mature stage or something. If the ancient sculk brain node becomes some kind of final boss, like the command block in CWSM, not only would that be awesome, but the warden could be a crucial part of the fight as well.

**Comment by Mikeatron-User** [comment]
The warden and sculk horde are separate entities. Feel free to speculate on what that means in terms of the lore. Also the warden was not made to be balanced for combat, using it as a unit is unbalanced.
