### ISSUE TITLE
Mobs don't spawn anymore

### ISSUE THREAD

**Issue by Verminator12** [TeamPeril/Sculk-Hoard#53]
Mobs don't spawn anywhere besides from mob spawners. I tested a bit to locate the issue. 

Step 1 - New world (mobs spawn)
Step 2 - Activate ancient node, the night after the activation no mob will ever spawn (night nor caves)

I tried going super far (10000,10000) from spawn and it doesn't change anything.

I am on Normal difficulty. Chunks load is 12. And the entity cap is close to zero out of 200.

**Comment by Mikeatron-User** [comment]
This will be resolved in next major update.

**Comment by Verminator12** [comment]
Hi, when will the next major update come ?

**Comment by Mikeatron-User** [comment]
> Hi, when will the next major update come ?

That update came in May 12th

**Comment by Verminator12** [comment]
I still have the issue on my server. Does your fix apply to existing games and also servers ?

**Comment by Mikeatron-User** [comment]
> I still have the issue on my server. Does your fix apply to existing games and also servers ?

Yes, just use the config to limit the population of sculk units.
