### ISSUE TITLE
TPS lag using latest beta

### ISSUE THREAD

**Issue by unweeked** [TeamPeril/Sculk-Hoard#54]
Using the latest beta5 of Sculk Horde creates giant lag spikes (tps). At least from what spark profiler showed.
![Picsart_24-05-17_15-01-28-842](https://github.com/TeamPeril/Sculk-Horde/assets/96650761/638bdc75-f03b-43b6-b420-5f45326087ab)
I can send my logs too if you want.

**Comment by Mikeatron-User** [comment]
Update the Mod
