### ISSUE TITLE
[Suggestion]: Potion of Darkness Resistance

### ISSUE THREAD

**Issue by ghost** [TeamPeril/Sculk-Hoard#58]
Given how the darkness effect is more prevalent from nodes, and how more dangerous fighting the Horde becomes with the Darkness Effect, I think a potion of Darkness Resistance should exist to ease on taking out nodes.

My take on a Potion of Darkness Resistance:
- Needs a Crying Soul as the brewing ingredient, base potion lasts for a minute.
- Can be upgraded with redstone to give 3 minutes of resistance.
![darkresist](https://github.com/TeamPeril/Sculk-Horde/assets/148708399/a3cbe1cb-e384-43b5-b491-8c28154f7f6f)

**Comment by Mikeatron-User** [comment]
I will consider this.
