### ISSUE TITLE
Sculk Horde Ticking Entity

### ISSUE THREAD

**Issue by haybail157** [TeamPeril/Sculk-Hoard#60]
The Sculk Horde (sculkhorde-1.20.1-0.9.8.jar) has been responsible for crashing my server (single tick took 60 seconds). 

The crash report indicates that it may be a movement issue to do with the Sculk Bee Nest. 

The line identified in the crash report is as follows: 

	at TRANSFORMER/sculkhorde@1.20.1-0.9.8-Beta2/com.github.sculkhorde.core.ModSavedData$BeeNestEntry.isEntryValid(ModSavedData.java:1081)
	
Will submit crash report and/or .log upon request.

**Comment by Mikeatron-User** [comment]
> The Sculk Horde (sculkhorde-1.20.1-0.9.8.jar) has been responsible for crashing my server (single tick took 60 seconds). 
> 
> The crash report indicates that it may be a movement issue to do with the Sculk Bee Nest. 
> 
> The line identified in the crash report is as follows: 
> 
> 	at TRANSFORMER/sculkhorde@1.20.1-0.9.8-Beta2/com.github.sculkhorde.core.ModSavedData$BeeNestEntry.isEntryValid(ModSavedData.java:1081)
> 	
> Will submit crash report and/or .log upon request.	

Please post any available logs
