### ISSUE TITLE
Entity Chunk Loading

### ISSUE THREAD

**Issue by MirokaSult** [TeamPeril/Sculk-Hoard#62]
Entity chunk loading just suddenly stopped working in my world. Did not update the mod or anything else, just saved the game, logged back in the next day and chunk loading is not working.

**Comment by Mikeatron-User** [comment]
> Entity chunk loading just suddenly stopped working in my world. Did not update the mod or anything else, just saved the game, logged back in the next day and chunk loading is not working.

Can you explain what you mean in more detail.

**Comment by MirokaSult** [comment]
> > Entity chunk loading just suddenly stopped working in my world. Did not update the mod or anything else, just saved the game, logged back in the next day and chunk loading is not working.
> 
> Can you explain what you mean in more detail.

So, I was just playing normally, made some progress, destroyed 2 nodes already, entity chunk load requests value was more than 2000 and chunks were definitely loaded, but when I once again saved and quit and logged back in after a day I noticed hostile mobs spawning, checked entity chunk load requests and the value was at 0, I made some tests and chunks were indeed not loaded. Can’t really explain more, so I can provide a link to download the world if you need to.

**Comment by Mikeatron-User** [comment]
This is behavior I've seen before. I will do a deeper investigation of this. For now, just relog.

**Comment by Mikeatron-User** [comment]
Has Since been Fixed
