### ISSUE TITLE
[Suggestion]: Provide matching leaves for Infested Log

### ISSUE THREAD

**Issue by liangcha385** [TeamPeril/Sculk-Hoard#64]
In some cases, a large number of bare tree trunks may not perfectly match the camouflage characteristics of Infested Log.
Can you provide camouflage leaves that match it.

**Comment by Mikeatron-User** [comment]
Can you provide an example?

**Comment by liangcha385** [comment]
When a tree is infected, its upper leaves will naturally fall and drop a large number of saplings, which in extreme cases can cause game lag
Can the leaves be preserved and converted into "Infested Leaves" to prevent lagging caused by a large amount of untreated fallen objects

_And a bunch of exposed tree trunks can make people feel strange_

**Comment by Mikeatron-User** [comment]
I've recently solved this issue with cursors consuming items from leaves. The look of bare tree trunks is intentional.
