### ISSUE TITLE
Main Structure Doesn't Generate

### ISSUE THREAD

**Issue by xXDragonBotXx** [TeamPeril/Sculk-Hoard#65]
Hello, I created my world and the mod on Forge 1.16.5. I don't know if in this version doesn't exist the main structure. But when I create my world and go to 0, 0 there isn't any structure, I used spectator gamemode to see to the surroundings but I don't see The Sculk Tomb.

Can someone help me? And sorry for the inconvenience.

**Comment by Mikeatron-User** [comment]
The Tomb does not exist in version 1.16.5

**Comment by xXDragonBotXx** [comment]
Oh alright, thank you.
