### ISSUE TITLE
Not compatible with Deeper And Darker mod

### ISSUE THREAD

**Issue by Hanwei233** [TeamPeril/Sculk-Hoard#68]
The game crashes when Deeper And Darker mobs are spawned

Crash report:
https://pastebin.com/d4JZCjys

**Comment by Mikeatron-User** [comment]
By any chance, did you mess with this mob's entity tags?

**Comment by Hanwei233** [comment]
I added some of DAD mobs to the tag "sculkhorde:entity_types/sculk_entity"

**Comment by Mikeatron-User** [comment]
> I added some of DAD mobs to the tag "sculkhorde:entity_types/sculk_entity"

Do not do this. Use `sculk_horde_do_not_attack` instead.
