### ISSUE TITLE
Crashes on launching minecraft

### ISSUE THREAD

**Issue by wgames445** [TeamPeril/Sculk-Hoard#7]
I have geckolib installed and whenever i try to launch minecraft with this mod enabled it crashes, but when I disable it minecraft launches fine

Crash logs:
https://paste.ee/p/3ibKr

**Comment by wgames445** [comment]
Sorry, ive solved this now, I had Geckolib 4.1.3 but I updated to 4.2 and it works.

**Comment by TeamPeril** [comment]
Glad to see it resolved. Thanks for reporting :)
