### ISSUE TITLE
Crash on loading a world

### ISSUE THREAD

**Issue by Cephelo** [TeamPeril/Sculk-Hoard#72]
Not sure why, but in the newest version (1.20.1-0.9.15), this crash happens upon trying to join a world, even one that's newly created.  
[crash-2024-09-19_02.25.23-server.txt](https://github.com/user-attachments/files/17055590/crash-2024-09-19_02.25.23-server.txt)
This does not occur in 0.9.14.

Also side note, but for some reason the Sculk Tomb doesn't always generate?  It wasn't there at all - maybe because the place it usually generates was overlapped by another structure?  Odd...

**Comment by mpustovoi** [comment]
> This does not occur in 0.9.18.

Where did you get that version?

**Comment by Cephelo** [comment]
Apologies, I meant 0.9.14 - the previous version.

**Comment by Mikeatron-User** [comment]
I will investigate this
