### ISSUE TITLE
World isnt loading with mod installed

### ISSUE THREAD

**Issue by pheeabee** [TeamPeril/Sculk-Hoard#74]
Ive been using this mod for a few months, but now whenever I try to log in the world never finishes loading, and I receive this error in the log reports. Removing the mod seems to fix the issue. 
![dasdsadaswsad](https://github.com/user-attachments/assets/1ef59011-bde8-4bb9-b2fd-f5d00834c3b1)
![image](https://github.com/user-attachments/assets/f59dc0f6-d0d0-4961-b268-4b047e7d2cab)

**Comment by pheeabee** [comment]
here's my log https://pastebin.com/Zn8fauT3

**Comment by Mikeatron-User** [comment]
Theres unfortunately nothing in the logs that indicate whats causing the world to fail to load.
