### ISSUE TITLE
How does this mod work in 1.20.1?

### ISSUE THREAD

**Issue by StormCircuit** [TeamPeril/Sculk-Hoard#8]
I loaded this mod up in a modpack but I am a bit confused as to how it operates and infects an entire world. The "sculk tomb" is a tiny pocket underground that spawns the sculk spreader seemingly randomly like any other structure, not the massive dungeon depicted on the wiki. The sculk its self does not spread unless:
A: a sculk spreader initially created it. This means a deep dark biome with sculk won't spread as far as I can tell, only these rarely generated structures
and
B: will only spread if the chunk the structure spawns in is loaded. This means that unless I get extremely unlucky I won't notice it in typical gameplay since I would need to be on top of a spreader building my base by pure chance.

Because the structure rarely spawns, and when it does due to a player exploring, it will likely be unloaded just as fast making a real threat unlikely. Case in point: I played regular survival for a bit and randomly found a place for a base. There was no sculk tomb structure nearby and therefore I never noticed the effects of this mod.

Furthermore is there no configuration file? I can't find it in serverconfig or the config folder nor did clothconfig find one anywhere. Let me know if I am mistaken with my understanding of how this mod works and if I am missing a way to configure it. If I found a bug I can make a proper issue report, I just wanted to make sure I am not mistaken. Nonetheless, the mod looks very cool and I look forward to figuring it out!

**Comment by StormCircuit** [comment]
I regret if I come off as ignorant or sassy. I changed the title to try and reflect that I am genuinely trying to get up to date information for 1.20.1 as the mod seems to have changed.

**Comment by StormCircuit** [comment]
Update: answered my own question. I had the release version of 1.20.1 which has no main tomb but just makes those small nodes. If you update to the latest beta, it makes the tomb. Once the tomb is opened it creates nodes (these are documented on the wiki) that forceload (chunkload) themselves as they spread through the world. This means it initially starts at 0,0 but slowly grows outward.

I also found in the latest version that those small little caves of spreaders do not spawn. This means the only vector for the infection is at the world spawn.

**Comment by Mikeatron-User** [comment]
Thanks for the feedback. I will improve our documentation to better reflect the changes in the newer updates. Apologies as I have been very busy.
