### ISSUE TITLE
[1.20.1] "disable_sculk_horde_unless_activated" config option cripples Ancient Node

### ISSUE THREAD

**Issue by Cephelo** [TeamPeril/Sculk-Hoard#82]
If the experimental "disable_sculk_horde_unless_activated" config option is set to true, then the Horde starts out as defeated.  I assume this is intended, since it effectively disabled a lot of their functions.  However, the Ancient Node cannot be awakened if in this state, and can only be awakened with commands.

Perhaps another state like "INERT" could be added, specifically for when this config option is enabled, and the Ancient Node has not yet been visited?  I would like to play with this option enabled, but using a command each time I visit the Ancient Node might get old quick for some people.  Just a thought

**Comment by Mikeatron-User** [comment]
This config option has always been broken, I'm going to remove it entirely
