### ISSUE TITLE
[Suggestion]: Arrows of Purity

### ISSUE THREAD

**Issue by Jouto25** [TeamPeril/Sculk-Hoard#83]
Another way to purify the Horde. These arrows are tipped in the same essence that is in the Flasks of Purity.

To craft Arrows of Purity, you surround an arrow with four Purity Essence, which gives you 16 arrows.

The arrows work like the flasks- the difference is that you can shoot the cure further with a bow or crossbow, but their effectiveness is worse than a Flask of Purity.

This gives the player another means to purify the world, allowing the player to snipe an infected area instead of more direct confirmation with the flasks.

**Concept of the Arrows of Purity:**
![Arrow of Purity](https://github.com/user-attachments/assets/2db3880f-7e61-4507-845a-31a4f95d3e65)

**Comment by Mikeatron-User** [comment]
Very good recommendation, perhaps I'll do something like this.
