### ISSUE TITLE
Spelling Issue in Wiki

### ISSUE THREAD

**Issue by EriX24** [TeamPeril/Sculk-Hoard#93]
https://github.com/TeamPeril/Sculk-Horde/wiki/Diseased-Cysts

"Cured" is spelt "Cursed".

**Comment by Mikeatron-User** [comment]
Thank you, it was fixed :)

**Comment by ScreamingMC** [comment]
however:

`"effect.sculkhorde.diseased_cysts.description": "Can damage and infect other entities near the initial victim. It can be cursed using a Purification Flask.",`


in game the lang file still has the error... but can be easily fixed with a resourcepack
